### ISSUE TITLE
Faire attention au return en jsx -> return (...);

### ISSUE THREAD

**Issue by nabdali** [ZenoQwy/reactJunia-Thomas#1]
C'est vraiment pas grave, mais il faut attention avec les return inline, il faut mieux utiliser les ( ) pour retourner des éléments JSX.
Au lieu de faire comme ça : 
```
function WelcomeMessage(props) {
            return <h1 style={{color: 'blue'}}>Bienvenue {props.name}</h1>;
        }
```
Il est préférable de comme suit : 

```
function WelcomeMessage(props) {
            return (
            <h1 style={{color: 'blue'}}>Bienvenue {props.name}</h1>
            );
        }
```

https://github.com/ZenoQwy/reactJunia-Thomas/blame/c45d002d6a8ef59d5a8e37e0501a103aa5043f47/lab%205.html#L74

**Comment by ZenoQwy** [comment]
Merci ! C'est corrigé
